Repository cse110-sp24-group9/CSE110-Project, pull requests merged in 2024-05, with the labels that each got.

#6 Pipe line
  .github/workflows/main.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement

#9 Create test
  __tests__/helloworld.test.js
  eslint.config.mjs
  package-lock.json
  package.json
Labels: enhancement

#11 added jest auto type sense for type completion
  package-lock.json
  package.json
Labels: documentation, enhancement

#42 Creat eventlist styling diagram
  specs/diagrams/eventlist_diagram.drawio.png
Labels: diagram

#47 created pipeline diagram
  admin/cipipeline/phase1.drawio.png
Labels: diagram

#51 Jsdoc auto bot
  .github/workflows/jsdoc.yml
  .jsdoc.json
  package-lock.json
  package.json
  source/place_holder
  source/place_holder.js
Labels: documentation, enhancement

#56 design and frontend meeting 510
  admin/meetings/Frontend_Design/0510-meeting-1.md
Labels: BackLogged

#67 Delete source/place_holder.js
  source/place_holder.js
Labels: bug

#85 Patch_fix_jsdoc_task_list
  package.json
  source/components/task-list-component.js
Labels: bug, Priority

#86 testing compat for caledar compoent
  source/components/CalendarItem.js
  source/pages/Calendar.html
Labels: enhancement, Tests
